package com.example.petapp.domain.model

/**
 * Domain representation of a single message stored in the database.
 *
 * Each message belongs to exactly one [branchId] and one [turnId].
 * Multiple messages (user, optional tool calls/results, assistant) share the same [turnId]
 * so they can be grouped into a [com.example.petapp.ui.MainViewModel.ChatTurn].
 *
 * @property id Auto-generated primary key (0 = not yet persisted).
 * @property branchId Branch this message belongs to; 1 = main branch.
 * @property turnId Groups all messages produced in one user↔agent round-trip.
 *   Generated by [com.example.petapp.ui.MainViewModel]'s `AtomicLong` counter.
 * @property role One of `"user"`, `"assistant"`, `"tool"`.
 * @property messageJson Full JSON serialization of the [com.example.petapp.data.Message]
 *   (including tool call metadata) used to reconstruct agent history on restore.
 * @property displayText Plain text shown in the chat bubble; null for invisible tool messages.
 * @property promptTokens Tokens consumed by the prompt in this turn (set only on the last assistant message).
 * @property completionTokens Tokens generated by the model (set only on the last assistant message).
 * @property totalTokens Sum of prompt + completion tokens.
 * @property cachedTokens Prompt tokens served from the KV-cache (reduces cost).
 * @property cost Estimated USD cost of the turn, or null if unknown.
 * @property durationSec Wall-clock seconds from request start to first token received.
 * @property timestamp Unix epoch milliseconds; offset by message index within a turn to preserve order.
 */
data class ChatMessage(
    val id: Long = 0,
    val branchId: Long = 1L,
    val turnId: Long,
    val role: String,
    val messageJson: String,
    val displayText: String?,
    val promptTokens: Int?,
    val completionTokens: Int?,
    val totalTokens: Int?,
    val cachedTokens: Int?,
    val cost: Double?,
    val durationSec: Double?,
    val timestamp: Long
)
